# FTR: Configuration on https://travis-ci.org/vector-im/riot-android/settings
#
# - Build only if .travis.yml is present -> On
# - Limit concurrent jobs                -> Off
# - Build pushed branches                -> On (build the branch)
# - Build pushed pull request            -> On (build the PR after auto-merge)
#
# - Auto cancel branch builds            -> On
# - Auto cancel pull request builds      -> On

language: android
jdk: oraclejdk8
sudo: false

notifications:
  email: false

android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - tools
    - platform-tools

    # The BuildTools version used by your project
    - build-tools-28.0.3

    # The SDK version used to compile your project
    - android-28

before_cache:
  - rm -fr $HOME/.gradle/caches

cache:
  directories:
# Travis is not happy with gradle cache (getting permission denied)
#   - $HOME/.gradle/caches/

# Build with the development SDK
before_script:
  - /bin/sh ./set_debug_env.sh

# Just build the project for now
script:
  # Build app (assembleAppRelease assembleAppfdroidRelease)
  # Build Android test (assembleAndroidTest)
  # Code quality (lintAppRelease lintAppfdroidRelease)
  - ./gradlew clean assembleAppRelease assembleAppfdroidRelease assembleAndroidTest lintAppRelease lintAppfdroidRelease --stacktrace
  # Run unitary test (Disable for now, see https://travis-ci.org/vector-im/riot-android/builds/502504370)
  # - ./gradlew testAppReleaseUnitTest --stacktrace
  # Other code quality check
  - ./tools/check/check_code_quality.sh
  - ./tools/travis/check_pr.sh
  # Check that indonesians file are identical. Due to Android issue, the resource folder must be value-in/, and Weblate export data into value-id/.
  - diff ./vector/src/main/res/values-id/strings.xml ./vector/src/main/res/values-in/strings.xml
